name: Deploy (VPS)
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}      # e.g., 203.0.113.10
          username: ${{ secrets.VPS_USER }}  # e.g., moose
          key: ${{ secrets.VPS_SSH_KEY }}    # your private key (no passphrase), added as Actions Secret
          script: |
            set -e
            # App directory on the server
            if [ ! -d /var/www/moosematrix ]; then
              sudo mkdir -p /var/www/moosematrix
              sudo chown -R $USER:$USER /var/www/moosematrix
            fi
            cd /var/www/moosematrix

            # First-time clone or update
            if [ ! -d .git ]; then
              git clone https://github.com/THE-MOOSE-MAN/moosematrix.git .
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            # Ensure Node 20 exists (install once on VPS, then skip)
            if ! command -v node >/dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install deps (root + packages + app)
            npm ci
            cd packages/ui && npm ci
            cd ../../apps/moosematrix && npm ci
            cd ../../

            # Build the app
            npx turbo run build --filter=moosematrix

            # Start or restart via PM2 (needs ecosystem.config.js)
            if ! command -v pm2 >/dev/null; then
              sudo npm i -g pm2
            fi
            pm2 startOrRestart ecosystem.config.js --only moosematrix
            pm2 save
