name: CI
on:
  push: { branches: [main] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Install root deps (includes turbo)
      - name: Install root deps
        run: npm ci

      # Install package deps (shared UI)
      - name: Install UI deps
        run: cd packages/ui && npm ci

      # Install app deps
      - name: Install app deps
        run: cd apps/moosematrix && npm ci

      # Sanity build (ensures Next compiles)
      - name: Build (moosematrix)
        run: npx turbo run build --filter=moosematrix
