name: Deploy MooseMatrix

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/the-moose-man/moosematrix:latest
            ghcr.io/the-moose-man/moosematrix:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            docker pull ghcr.io/the-moose-man/moosematrix:latest

            # Stop/remove any old container
            docker stop moosematrix-app || true
            docker rm moosematrix-app || true

            # Ensure env file directory exists
            mkdir -p /var/www/moosematrix

            # Run new container with restart policy + env file
            docker run -d \
              --restart always \
              --env-file /var/www/moosematrix/.env \
              -p 127.0.0.1:3000:3000 \   # bind only to localhost
              --name moosematrix-app \
              ghcr.io/the-moose-man/moosematrix:latest

      